enum Type {
  GET_NOTE_FROM_USER = "GET_NOTE_FROM_USER",
  DELETE_NOTE = "DELETE_NOTE",
  UPDATE = "UPDATE",
  NAVIGATE_TO = "NAVIGATE_TO",
  UPDATE_CLICKED = "UPDATE_CLICKED",
}

export default Type
